# Site settings
title: Online Mapping Info
description: Examples and concepts for online mapping
author: Craig Stuart Sapp
#email:
baseurl: "/"
url: "https://map-info.sapp.org"

# Use the remote theme from GitHub Pages' theme repository
remote_theme: pages-themes/minimal
# remote_theme: pages-themes/minimal@v0.2.0  # You can specify a version or omit it
# remote_theme: pages-themes/cayman
# remote_theme: pages-themes/dinky
# remote_theme: pages-themes/hacker
# remote_theme: pages-themes/leap-day
# remote_theme: pages-themes/midnight
# remote_theme: pages-themes/modernist
# remote_theme: pages-themes/slate
# remote_theme: pages-themes/tactile
# remote_theme: pages-themes/time-machine

plugins:
  - jekyll-remote-theme # Make sure this plugin is enabled

# Markdown settings
markdown: kramdown
highlighter: rouge

# Exclude from processing
exclude:
  - README.md

# Default layout for pages (not home)
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: page

# Set a custom layout for the homepage
defaults:
  - scope:
      path: ""
      type: homepage
    values:
      layout: home

custom_css: /assets/styles.css
